source 'https://rubygems.org'

gem 'kitchen-vagrant'
gem 'kitchen-azurerm'
gem 'kitchen-ec2'
gem 'kitchen-google'
gem 'chef-cli'
gem 'kitchen-puppet'
gem 'puppet'
gem 'kitchen-ansible'
gem 'kitchen-inspec'
